version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - activity-service

  activity-service:
    build: .
    restart: always
    environment:
      - DATABASE_URL=mongodb://mongo/activityDB
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    container_name: mongo-poc
    image: mongo
    restart: always
    ports:
      - "27017:27017"
