apiVersion: v1
kind: ConfigMap
metadata:
  name: activity-service-config
  namespace: activity-service
data:
  DATABASE_URL: "mongodb://mongo-service:27017/activityDB?maxPoolSize=1000&connectTimeoutMS=30000"
  NODE_ENV: "production"
  PORT: "3001" 